rust-lang/jobserver-rs

src/lib.rs
Just because libc has the symbol, doesn't mean the kernel supports it.
Based on rust-lang/rust#42521.
=> Handle ENOSYS when calling `pipe2`

src/lib.rs
Background: I'm planning to write a system-wide jobserver implementation. It uses sockets, not pipe, which will be rejected with the current validation.
Reference implementation in make: https://github.com/mirror/make/blob/48c8a116a914a325a0497721f5d8b58d5bba34d4/src/posixos.c#L124
Also in the docs:
> If your tool determines that the --jobserver-auth option is available in MAKEFLAGS but that the file descriptors specified *are closed*,
So we don't need to force them to be a pipe.
=> Validate jobserver fd more conservatively

src/lib.rs
Cross process jobserver and thread cancellation is not supported
This is part of an experiment to port rustc to wasi. (cc https://github.com/rust-lang/miri/issues/722)
cc @RReverser
=> Add support for non-unix and non-windows platforms

src/lib.rs
When building with sccache locally, I'm seeing a bunch of errors to acquire the
jobserver token which are caused by interrupts at bad times.
I think it was a kernel update what caused this, fwiw, but not 100% sure.
Both can happen according to the man pages, and we're not handling them
sensibly.
I think retrying the read / poll when the error is EINTR is a sensible thing to
do.
=> Handle EINTR.

src/lib.rs, src/unix.rs
For some reason, it's only set on Unix, not Windows, but some versions
of GNU make will complain about "-jN forced in submake" when _no_ -j flag
is given at all, and disable the jobserver mode entirely.
=> Set the -j flag in make flags on all platforms

src/lib.rs, src/unix.rs, tests/client-of-myself.rs, tests/client.rs, tests/helper.rs, tests/make-as-a-client.rs, tests/server.rs
I also remove now unneeded `extern crate` statement since this crate uses 2018 edition.
=> Fix some clippy warnings

src/unix.rs
Linux 5.6 and up optimize the wakeups of pipe readers
when pipes have multiple readers and those readers are blocking.
Always polling defeats that optimization.
https://github.com/torvalds/linux/commit/0ddad21d3e99c743a3aa473121dc5561679e26bb
fixes #30
=> Try blocking reads first to avoid thundering herd problem

src/unix.rs, tests/server.rs
This commit attempts to address rust-lang/cargo#9739 by optionally
increasing the capacity of pipes created on Linux. This may be required
if the pipe initially starts out with only one page of buffer which
apparently means that normal jobserver usage might cause the pipe to
deadlock where all writers are blocked.
=> Optionally increase the size of the pipe buffer

src/unix.rs, tests/server.rs
This reverts commit 865b7e375a29afbc8283f14729d4663daa858a1e.
Lots of errors about "can't increase jobserver limits" are cropping up in https://github.com/rust-lang/rust/issues/88091, and nothing was really that broken before so let's back this out and figure out a better way to deal with this later.
=> Revert "Optionally increase the size of the pipe buffer"

Cargo.toml, tests/client.rs, tests/make-as-a-client.rs, tests/server.rs
as the tempdir crate have been superceded by tempfile
=> Replace tempdir with tempfile

src/lib.rs
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>
=> Fix Safety doc for unsafe fn `Client::from_env`

src/lib.rs
Fixed #24 
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>
=> Add `configure_make`: Set `MAKEFLAGS` & `MFLAGS`

src/lib.rs, src/unix.rs, src/wasm.rs, src/windows.rs, tests/server.rs
Returns amount of tokens in the read-side pipe (number of jobs that could be started).
=> Add `available` traits to find out how many client tokens are unused

.github/workflows/main.yml, src/lib.rs, src/unix.rs
GNU `make` 4.4, released in October 2022[^1]. The jobserver defaults
to use named pipes (via `mkfifo(3)`) on supported platforms by
introducing a new IPC style `--jobserver-auth=fifo:PATH`, which `PATH`
is the path of fifo[^2].
This commit makes sure that the new style `--jobserver-auth=fifo:PATH`
can be forwarded to inherited processes correctly.
The support of creating a new client with named pipe will come as a
follow-up pull request.
[^1]: https://lists.gnu.org/archive/html/info-gnu/2022-10/msg00008.html
[^2]: https://www.gnu.org/software/make/manual/html_node/POSIX-Jobserver.html
=> Support `--jobserver-auth=fifo:PATH`

src/error.rs, src/lib.rs, src/unix.rs, src/wasm.rs, src/windows.rs
Continue implementing #51. The previous PR wasn't finished and cleaned up.
If we want to discern different errors and treat them differently, more specific return type would be more convenient.
If this's going to be merged, probably there'll be some changes from current version. If it's possible, i'd like to clean up results before merging.
=> Error type for `from_env_ext` function

src/error.rs, src/lib.rs
Continue #51 implementation
It's [possible](https://www.gnu.org/software/make/manual/html_node/Options_002fRecursion.html) that env var exists but doesn't contain jobserver. We'd like to discern this situation from `CannotParse` error.
=> Error type for from_env_ext function: update

.github/workflows/main.yml, Cargo.toml
Some new API were already used
* format arg capture (1.58)
* `std::os::fd` (1.66)
A bump is inevitably coming.
=> chore: set MSRV to 1.66 and edition to 2021

.github/workflows/main.yml, Cargo.toml, src/error.rs
I noticed that a patch version increment has caused other crates MSRV values to change, such as the zstd crate: https://github.com/gyscos/zstd-rs/issues/253
This MR changes the RawFd type to one present in older versions of rust, so that the MSRV can be reduced to 1.63.
My understanding is that this type should be equivalent because it's gated against `#[cfg(unix)]`, and so the benefits of `std::os::fd::RawFd` also supporting WASM is negated. https://github.com/rust-lang/rust/issues/98699
In theory the MSRV of the crate library is 1.60, but there are dev-dependencies that require 1.63 which would break the MSRV testing workflow (rustix, required by tempfile). 
If we insist on keeping the usage of `std::os::fd::RawFd`, I can feed back to the zstd crate and ask them to bump their MSRV …
=> Reduce MSRV to 1.63 with minor change in RawFd type

src/lib.rs
From the GNU make manual[^1]:
> Be aware that the `MAKEFLAGS` variable may contain multiple
> instances of the `--jobserver-auth=` option.
> Only the last instance is relevant.
Hence this commit makes it so.
With this commit, `--jobserver-auth` also takes precedence over
`--jobserver-fds`, even when `--jobserver-fds` is the last instance
of these flags. This is made intentionally since `--jobserver-fds`
was an undocumented internal-only flag before `--jobserver-auth`
made public, according to this announcement[^2].
[^1]: https://www.gnu.org/software/make/manual/make.html#Job-Slots
[^2]: https://git.savannah.gnu.org/cgit/make.git/tree/NEWS?h=4.2#n31
fixes #66
=> fix: last `--jobserver-auth` wins 

src/error.rs, src/unix.rs
According to the [GNU make manual](https://www.gnu.org/software/make/manual/make.html#POSIX-Jobserver):
> If either or both of these file descriptors are negative, it means the jobserver is disabled for this process.
This pr makes so.
From https://github.com/rust-lang/rust/issues/120515.
=> disable jobserver on unix, if file descriptors are negative

src/lib.rs, src/unix.rs
So that it can be used in different crates without causing UB.
[`opencv-rust`](https://github.com/twistedfall/opencv-rust) uses `jobserver::Client::from_env` in its `build.rs` to parallelize generation of bindings, then call `cc::Build::compile` with features `cc/parallel` enabled it will also call `jobserver::Client::from_env` and creates a UB https://github.com/rust-lang/cc-rs/issues/844#issuecomment-1663960861
Workaround for this will require either wrapping `jobserver::Client` with `std::mem::ManuallyDrop`, or switching to my fork [`jobslot`](https://docs.rs/jobslot) which supports calling `Client::from_env` unlimited number of times.
This PR thus port the change to upstream so that any crate using `jobserver` can benefit from this and can stop worrying about UB caused by calling …
=> feat: Make `Client::from_env` safe to call for any number of times

.github/actions/compile-make/action.yml, .github/workflows/main.yml, .gitignore, Cargo.lock, Cargo.toml, src/lib.rs, src/unix.rs, src/wasm.rs, src/windows.rs
=> feature: Impl `Client::{supports_try_acquire, try_acquire}`

src/unix.rs
Technicially it is also available on musl libc 1.2.5,
yet the libc@0.2.153 (lastet) doesn't export the symbol,
and that version of musl libc is too new (released in 2024-03)
Fixes #79. Tested against Rust docker image [alpine3.18](https://github.com/rust-lang/docker-rust/blob/73b57d936481598421d27c4d722a24774a2267ea/1.77.2/alpine3.18/Dockerfile)
=> fix: preadv2 only available on GNU libc

src/wasm.rs
The wasm target's `Client::try_acquire` method doesn't compile because the return value doesn't match the method's signature. This PR fixes that by wrapping the return value in a `Result` which adheres to the method's signature.
=> fix try_acquire for wasm target

src/unix.rs
This optimization has introduced many compatibility issues, so remove it for now until we find it worthy the investment.
See also
* <https://github.com/rust-lang/cc-rs/issues/1039>
* <https://github.com/rust-lang/jobserver-rs/issues/87>
=> fix: remove preadv2 optimization

src/error.rs, src/lib.rs, src/unix.rs
=> Fix `Client::configure*` on unix

.github/workflows/publish.yml
<https://github.com/rust-lang/infra-team/issues/117>
This would make it easier to release new crate, without having to ping anyone.
Whoever has the right to create a new release on GitHub shall have the right to publish it to crates.io
**NOTE that this new workflow requires a secret `CARGO_REGISTRY_TOKEN` to be set.
With scoped token, you can limit the token to only have the ability to publish new version under name `jobserver`, and nothing else.**
=> CI: Support automatic publish to crates.io on tag creation

src/windows.rs
Jobserver is specifying external functions without also declaring a dependency on the relevant import library that contains those functions. While `kernel32` will often be linked by *something*, the same can not be said for `advapi32`. As a bonus this is mildly more efficient.
In the future we could use `raw-dylib` to avoid the need for import libs entirely (requires msrv to be 1.65+),
=> Declare Windows imports jobserver depends on

Cargo.lock, Cargo.toml, src/windows.rs
The reason `getrandom` isn't currently used is given by: https://github.com/rust-lang/jobserver-rs/blob/f494d826e436a7027f40affa504cb8777923d108/src/windows.rs#L71-L76 which says `getrandom` can't be used due to https://github.com/rust-lang/rust/issues/65014 which was closed as an instance of https://github.com/rust-lang/cargo/issues/4866 which is closed in favour of a nightly cargo feature https://github.com/rust-lang/cargo/issues/7915 which has since been stabilised.
So I think we're good now.
=> Use getrandom for randomness

src/unix.rs
Miri doesn't currently support mkfifo, so can't present named pipes for other processes (but spawning processes isn't possible from miri anyway) And it also isn't possible in miri to get fd's inherited from the parent process. But this is enough for what running rustc in miri needs.
Fixes https://github.com/rust-lang/jobserver-rs/issues/108
=> Fix running inside miri when using in-process accounting
